/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "done": { "creationFunction": "CreateGlassButton", "onclick": "showFront", "text": "Done" },
    "image": { "view": "DC.ImageLayout" },
    "image1": { "view": "DC.ImageLayout" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack" },
    "text1": { "text": "Xcode Shortcuts Guide\n\nCreated by Colin Wheeler 2/25/2008\nUpdated 3/9/2011 for 4.0\nwww.cocoasamurai.com\n", "view": "DC.Text" },
    "text2": { "text": "The Xcode Shortcuts Guide is licensed under the Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License (http://creativecommons.org/licenses/by-nc-sa/3.0/ ).\n\nAlthough it's not required,I ask if you make a derivative work to just let me know at cocoasamurai@gmail.com. \n\nHave fun!\n\n\nSupa-lame Dashboard widget by Mark Kirk 4/7/2011\n", "view": "DC.Text" }
};



